//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalExamination
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> ExaminationDate { get; set; }
        public Nullable<bool> Examined { get; set; }
        public Nullable<int> Doctor_id { get; set; }
        public Nullable<int> Patient_id { get; set; }
        public Nullable<int> ExaminationType_id { get; set; }
        public Nullable<int> WaitingRoom_id { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual ExaminationType ExaminationType { get; set; }
        public virtual WaitingRoom WaitingRoom { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
