//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalFinding
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Doctor_id { get; set; }
        public Nullable<int> Patient_id { get; set; }
        public Nullable<int> C_findingDesc_id { get; set; }
        public Nullable<int> MedicalDiagnosis_id { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual MedicalDiagnosi MedicalDiagnosi { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual MedicalFindingDescription MedicalFindingDescription { get; set; }
    }
}
